# Generated by Django 2.2.14 on 2020-07-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200713_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='owner',
        ),
        migrations.AlterField(
            model_name='animal',
            name='animaltype',
            field=models.CharField(choices=[('ca', 'Кот'), ('he', 'Ёж')], max_length=2, verbose_name='Вид питомца'),
        ),
    ]
